const posts = [
    {imgCard : "/thumbnail-2.png",
    tag : "INTERNET",
    date: "June 28, 2021",
    title: "How to design a product that can grow itself 10x in year",
    description : "Auctor Porta. Augue vitae diam mauris faucibus blandit elit per, feugiat leo dui orci. Etiam vestibulum. Nostra netus per conubia dolor.",
    imgProfile: "/author-2.png",
    name : "Jenny Wilson",
    job: "Product Designer",
    },
    {imgCard : "/thumbnail-3.png",
    tag : "9 TO 5",
    date: "June 22, 2021",
    title: "The More Important the Work, the More Important the Rest",
    description : "Suitable Quality is determined by product users, clients or customers, not by society in general. For example, a low priced product may be viewed as having high.",
    imgProfile: "/author-3.png",
    name : "Esther Howard",
    job: "Entrepreneur",
    },
    {imgCard : "/thumbnail-4.png",
    tag : "INSPIRATIONS",
    date: "June 18, 2021",
    title: "Email Love - Email Inspiration, Templates and Discovery",
    description : "Consider that for a moment: everything we see around us is assumed to have had a cause and is contingent upon something else.",
    imgProfile: "/author-4.png",
    name : "Robert Fox",
    job: "Front-end Engineer",
    },
    {imgCard : "/thumbnail-5.png",
    tag : "9 TO 5",
    date: "June 22, 2021",
    title: "The More Important the Work, the More Important the Rest",
    description : "Suitable Quality is determined by product users, clients or customers, not by society in general. For example, a low priced product may be viewed as having high.",
    imgProfile: "/author-3.png",
    name : "Esther Howard",
    job: "Entrepreneur",
    },
    {imgCard : "/thumbnail-7.png",
    tag : "INSPIRATIONS",
    date: "June 18, 2021",
    title: "Email Love - Email Inspiration, Templates and Discovery",
    description : "Consider that for a moment: everything we see around us is assumed to have had a cause and is contingent upon something else.",
    imgProfile: "/author-4.png",
    name : "Robert Fox",
    job: "Front-end Engineer",
    },
    {imgCard : "/thumbnail-6.png",
    tag : "INTERNET",
    date: "June 28, 2021",
    title: "How to design a product that can grow itself 10x in year",
    description : "Auctor Porta. Augue vitae diam mauris faucibus blandit elit per, feugiat leo dui orci. Etiam vestibulum. Nostra netus per conubia dolor.",
    imgProfile: "/author-2.png",
    name : "Jenny Wilson",
    job: "Product Designer",
    },
]

export default posts
