export {default as Navbar} from './Navbar/Navbar'
export {default as FeaturedPost} from './Post/FeaturedPost/FeaturedPost'
export {default as CardPost} from './Post/CardPost/CardPost'
export {default as posts} from './Post/CardPost/posts'
export {default as Footer} from './Footer/Footer'